#!/bin/bash

##
## Work with an offline library
##

config_file=$HOME/.config/libraryassist/config
if [ -f $config_file ] ; then
  . $config_file
else
  echo "No config file found: $config_file"
  exit
fi

usage() {
  cmd=$(basename $0)
  echo "Usage: $cmd -a get-all"
  echo "Usage: $cmd -a push-all"
}

while getopts "ha:" o; do
  case "$o" in
    a) action=$OPTARG ;;
    h) usage ;;
    *) usage ;;
  esac
done


root=$(dirname $0)
dest=$root/pdf
sources=$root/sources

case $action in
  get-all)
    mkdir -p $dest

    for file in $sources/*.txt ; do
      category=$(basename $file .txt)
      mkdir -p $dest/$category

      cat $file | while read line ; do
        url=$(echo $line | cut -d'|' -f 1)
        if [ -z "$url" ] ; then
          continue
        fi

        label=$(echo $line | cut -d'|' -s -f 2)
        if [ -n "$label" ] ; then
          path=$(echo  $label | sed 's/ /_/g').pdf
        else
          path=$(basename $url)
        fi

        output=$dest/$category/$path
        if [ ! -f $output ] ; then
          echo "$category: $path ($url)"
          curl -s $url > $output
        fi
      done
    done
    ;;

  push-all)
    cd $dest
    aws --profile=$S3_PROFILE s3 sync . $S3_DEST
    ;;

  *) usage ;;
esac
