#!/bin/bash

##
## command line tools for working with YouTube.
## See: https://developers.google.com/youtube/v3/docs/
##

config=$HOME/.config/youtubeassist/config

if [ -f "$config" ] ; then
  . $config
else
  echo "Missing config file: $config"
  exit
fi

API_BASE=https://www.googleapis.com/youtube/v3

function usage() {
  cmd="Usage: $(basename $0)"
  echo "$cmd: -a init"
  echo "$cmd: -a subscriptions"
  echo "$cmd: -a subscription-delete -i id"
  echo "$cmd: -a playlists"
  echo "$cmd: -a playlist-items -i id"
  echo "$cmd: -a playlist-delete -i id"
  echo "$cmd: -a playlist-rename -i id -n new-name"
  echo "$cmd: -a playlist-create -n"
  echo "$cmd: -a video -i id"
  echo "$cmd: -a my-channel -i id"
  exit
}

age() {
  case $(uname) in
    Darwin) date=gdate ;;
    *) date=date ;;
  esac

  before=$($date +%s -d "$1")
  now=$($date +%s)
  echo $(((now - before) / (60 * 60 * 24)))
}

function filter {
  if [ -z "$VERBOSE" ] ; then
    jq "$@"
  else
    cat
  fi
}

while getopts ":a:i:n:v" opt ; do
  case $opt in
    a) ACTION=$OPTARG ;;
    v) VERBOSE=yes    ;;
    i) ID=$OPTARG     ;;
    n) NAME=$OPTARG     ;;
    \?) usage         ;;
  esac
done

function invoke {
  curl -s -H "Authorization: Bearer $AUTH_TOKEN" "$@" > /tmp/yt.buffer.$$
  next_page=`jq -r '.nextPageToken' < /tmp/yt.buffer.$$`

  if [ "$next_page" = "null" -o -z "$next_page" ] ; then
    cat /tmp/yt.buffer.$$
    rm -f /tmp/yt.buffer.$$
  else
    jq '.items'  < /tmp/yt.buffer.$$ | sed 's/^.//'> /tmp/yt.master.$$
    while [ "$next_page" != "null" ] ; do
      curl -s -H "Authorization: Bearer $AUTH_TOKEN" "$@" -d pageToken=$next_page |
        tee /tmp/yt.buffer.$$ |
        ( echo "," ; jq '.items' | sed 's/^.//' ) >> /tmp/yt.master.$$
      next_page=`jq -r '.nextPageToken' < /tmp/yt.buffer.$$`
    done
    rm -f /tmp/yt.buffer.$$
    echo '{ "items" : [ '
    cat /tmp/yt.master.$$
    echo ' ] }'
    rm -f /tmp/yt.master.$$
  fi
}

case $ACTION in
  init)
    gapi_auth -i $CLIENT_ID -p $CLIENT_SECRET  -r $AUTH_REDIRECT_URI -s "$API_SCOPE" init
    exit
    ;;

  my-channel)
    invoke -G $API_BASE/channels \
           -d mine=true \
           -d part=snippet,contentDetails,statistics \
           -d maxResults=50 |
      filter -r '.'
    ;;
  
  subscriptions)
    invoke -G $API_BASE/subscriptions \
           -d mine=true \
           -d part=snippet \
           -d maxResults=50 | 
      filter -r ' .items[] |  .id + ":" + .snippet.title'
    ;;

  subscription-delete)
    if [ -z "$ID" ] ; then
      echo "Deleting a subscription requires an ID (-i) value"
      usage
    fi
    invoke -X DELETE "$API_BASE/subscriptions?id=$ID"
    ;;

  playlists)
    invoke -G $API_BASE/playlists \
           -d mine=true \
           -d part=snippet \
           -d maxResults=50 | 
      filter -r ' .items[] |  .id + ":" + .snippet.title'
    ;;

  playlist-items)
    if [ -z "$ID" ] ; then
      echo "Missing -i id"
    fi

    invoke -G $API_BASE/playlistItems \
           -d part=id,snippet,contentDetails,status \
           -d playlistId=$ID \
           -d maxResults=50 |
      filter -r '.items[] | .contentDetails.videoId + "|" + .snippet.publishedAt + "|" + .snippet.title' > $HOME/.yt.buffer
    if [ -n "$VERBOSE" ] ; then
       cat $HOME/.yt.buffer
    else
      cat $HOME/.yt.buffer | while read line ; do
        id=$(echo $line | cut -d'|' -f1)
        added=$(echo $line | cut -d'|' -f2)
        age=$(age $added)
        title=$(echo $line | cut -d'|' -f2)
        echo "$id|$age|$title"
      done
    fi
    ;;

  
  playlist)
    if [ -z "$ID" ] ; then
      echo "Listing a playlist requires a playlist ID"
      usage
    fi
    invoke -G $API_BASE/playlistItems \
           -d playlistId=$ID \
           -d part=snippet,status \
           -d maxResults=50 |
      filter -r ' .items[] | .id + ":" + .snippet.resourceId.videoId + ":" + .snippet.title'
    ;;

  playlist-delete)
    if [ -z "$ID" ] ; then
      echo "Deleting a playlist requires an ID (-i) value"
      usage
    fi
    invoke -X DELETE "$API_BASE/playlists?id=$ID"
    ;;

  playlist-rename)
    if [ -z "$ID" -o -z "$NAME" ] ; then
      echo "Renaming a playlist requires you set the ID (-i) and NAME (-n)"
      usage
    fi
    invoke -X PUT "$API_BASE/playlists?part=snippet" \
           -H 'Content-Type: application/json' \
           -d "{'id': '$ID', 'snippet': {'title' : '$NAME'} }" |
      filter -r '.id + ":" + .snippet.title'
    ;;

  playlist-create)
    if [ -z "$NAME" ] ; then
      echo "Creating a playlist requires you set the NAME (-n)"
      usage
    fi
    invoke -X POST "$API_BASE/playlists?part=snippet,status" \
           -H 'Content-Type: application/json' \
           -d "{'snippet': {'title' : '$NAME'}, 'status' : {'privacyStatus' : 'public'} }" |
      filter -r '.id + ":" + .snippet.title'
    ;;

  video)
    if [ -z "$ID" ] ; then
      echo "Video info requires an ID (-i)"
      usage
    fi
    invoke -G $API_BASE/videos \
           -d id=$ID \
           -d part=snippet \
           -d maxResults=50 |
      filter -r '.items[] | .id + ":" + .snippet.title'
    ;;

  *)
    usage
    ;;
esac

