#!/bin/env python3

##
## Inspired by:
##  https://stackoverflow.com/questions/2693820/extract-images-from-pdf-without-resampling-in-python
##
## Useful for extracting images from a PDF
##
## Dependencies:
##  pip install --upgrade pymupdf
##  pip install tqdm
import os
import fitz
from tqdm import tqdm
import getopt, sys


def usage():
    cmd = os.path.basename(sys.argv[0])
    print("Usage:", cmd, "-h")
    print("Usage:", cmd, "-i file.pdf -o dir")
    exit()

argumentList = sys.argv[1:]
options = "ho:i:"
input_path = False;
output_dir = False;

arguments, values =  getopt.getopt(argumentList, options)
for arg, val in arguments:
    if arg in ("-h"):
        usage()
    elif arg in ("-i"):
        input_path = val
    elif arg in ("-o"):
        output_dir = val


if (not input_path) or (not output_dir):
    usage();

doc = fitz.Document(input_path)


for i in tqdm(range(len(doc)), desc="pages"):
    for img in tqdm(doc.get_page_images(i), desc="page_images"):
        xref = img[0]
        image = doc.extract_image(xref)
        pix = fitz.Pixmap(doc, xref)
        pix.save(os.path.join(output_dir, "%s_p%s-%s.png" % (os.path.basename(input_path)[:-4], i, xref)))
