#!/bin/bash

##
## Run gemini queries
##
## https://ai.google.dev/gemini-api/docs/image-generation#rest
##

CMD=$(basename $0)
TMP=$HOME/.tmp/$CMD ; mkdir -p $TMP

usage() {
  echo "Usage: $CMD -a generate-image -p prompt [-f image] [-v] [-y youtube-video-url-or-id]"
  echo "Usage: $CMD -a ask -p prompt [-v] [-f file]"
  exit 1
}

jqf() {
  if [ -z "$V" ] ; then
    jq "$@"
  else
    cat
  fi
}

case $(uname) in
  Darwin)
    BASE64_DECODE="base64 -d -o -" ;;
  *)
    BASE64_DECODE="base64 -d" ;;

esac

unset V ACTION PROMPT FILE

while getopts "a:p:hf:vy:" o; do
  case "$o" in
    p) PROMPT=$OPTARG  ;;
    a) ACTION=$OPTARG ;;
    f) FILE=$OPTARG ;;
    y) VIDEO_ID=$OPTARG ;;
    v) V=yes ;;
    * | h) usage  ;;
  esac
done

if [ -z "$GEMINI_API_KEY" ] ; then
  echo "No GEMINI_API_KEY env variable set."
  exit
fi
case "$ACTION" in
  ask)
    if [ -z "$PROMPT" ] ; then
      echo "Missing -p prompt"
      exit
    fi

    if [ -n "$VIDEO_ID" ] ; then
      youtubeassist -a subtitles -i "$VIDEO_ID" > $TMP/yt.subtitles
      if [ $? -ne 0 ] ; then
        echo "Couldn't extract YT Subtitles"
        exit 1
      fi
      FILE=$TMP/yt.subtitles
    fi

    inline=""
    if [ -n "$FILE" ] ; then
      if [ ! -f "$FILE" ] ; then
        echo "-f $FILE doesn't exist"
        exit
      fi

      stuff=$(base64 -w0 "$FILE")
      mt=$(file --mime-type "$FILE" | sed 's/^.*: *//')
      case "$mt" in
        text/*) mt=text/plain ;;
        image/*) mt=$mt ;;
        *) echo "Unsupported mime type. Maybe. $mt" ; exit
      esac

      inline=", { \"inline_data\": { \"mime_type\":\"$mt\", \"data\": \"$stuff\" } }"
    fi

    echo "{ \"contents\": [ { \"parts\": [ { \"text\": \"$PROMPT\" } $inline ] } ] }" > $TMP/ask.contents

    curl -s "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent" \
         -H 'Content-Type: application/json' \
         -H "X-goog-api-key: $GEMINI_API_KEY" \
         -X POST \
         -d "@$TMP/ask.contents" |
      jqf -r '.candidates[] | .content.parts[] | .text'
    ;;

  generate-image)
    if [ -z "$PROMPT" ] ; then
      echo "Missing -p prompt"
      exit
    fi


    inline=""
    if [ -n "$FILE" ] ; then
      if [ ! -f "$FILE" ] ; then
        echo "-f $FILE doesn't exist"
        exit
      fi

      img=$(base64 -w0 "$FILE")
      inline=", { \"inline_data\": { \"mime_type\":\"image/jpeg\", \"data\": \"$img\" } }"
    fi

    echo "{ \"contents\": [{ \"parts\": [ {\"text\": \"$PROMPT\"} $inline ] }] }" > $TMP/request.json
    curl -s -X POST \
         "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image-preview:generateContent" \
         -H "x-goog-api-key: $GEMINI_API_KEY" \
         -H "Content-Type: application/json" \
         -d  @$TMP/request.json |
      if [ -n "$V" ] ; then
        cat
      else
        jq -r '.candidates[0].content.parts[] | select(.inlineData) | .inlineData.data' | $BASE64_DECODE
      fi
    ;;

  '') usage ;;
  *) echo "Unknown action: $ACTION" ; exit ;;
esac
